/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tamarozzi.ui.panel;

import br.com.tamarozzi.controller.TarefaCategoriaController;
import br.com.tamarozzi.controller.TarefaController;
import br.com.tamarozzi.interfaces.MyAbstractPanelModel;
import br.com.tamarozzi.interfaces.Observable;
import br.com.tamarozzi.interfaces.Observer;
import br.com.tamarozzi.model.Tarefa;
import br.com.tamarozzi.model.TarefaCategoria;
import br.com.tamarozzi.model.UsuarioLogado;
import br.com.tamarozzi.ui.FrmCadastroTarefa;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Panda
 */
public class PanelTarefa extends javax.swing.JPanel implements MyAbstractPanelModel, Observable, Observer {

    private List<Observer> observers;
    
    private TarefaController tarefaController;
    private TarefaCategoriaController tarefaCategoriaController;
    
    private FrmCadastroTarefa frmCadastroTarefa;
    
    private List<String> listCampoFiltro;
    private List<String> listSituacaoFiltro;
    private List<TarefaCategoria> listCategoriasFiltro;
    private List<String> listResponsaveisFiltro;
    private List<String> listTipoDataFiltro;
    
    /**
     * Creates new form PanelTarefa
     */
    public PanelTarefa() {
        preInitComponents();
        initComponents();
        setView();
    }
    
    private void preInitComponents() {
        this.observers = new ArrayList<>();
        
        //Filters
        this.listCampoFiltro = Arrays.asList("search", "descricao");
        this.listSituacaoFiltro = Arrays.asList(null, "true", "false");
        this.listResponsaveisFiltro = Arrays.asList(null, UsuarioLogado.getInstance().getUUID());
        this.listTipoDataFiltro = Arrays.asList("cadastro", "vencimento", "conclusao");
        
        //Controllers
        this.tarefaController = new TarefaController();
        this.tarefaCategoriaController = new TarefaCategoriaController();
    }
    
    public final void setView() {
        this.setTarefaCategorias();
    }
    
    private void setTarefaCategorias() {
        this.cbxCategoria.removeAllItems();
        this.listCategoriasFiltro = new ArrayList<>(0);
        this.listCategoriasFiltro.add(new TarefaCategoria("Todos"));
        
        this.listCategoriasFiltro.addAll(tarefaCategoriaController.getAllTarefaCategoria("search", ""));
        
        if(this.listCategoriasFiltro != null) {
            for(TarefaCategoria c : this.listCategoriasFiltro) {
                this.cbxCategoria.addItem(c.getDescricao());
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPeriodo = new javax.swing.JLabel();
        dtcDataInicio = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        dtcDataFim = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        lblDataDe = new javax.swing.JLabel();
        cbxDataDe = new javax.swing.JComboBox<>();
        lblTarefas = new javax.swing.JLabel();
        cbxTarefas = new javax.swing.JComboBox<>();
        lblSituacao = new javax.swing.JLabel();
        cbxSituacao = new javax.swing.JComboBox<>();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        lblEm = new javax.swing.JLabel();
        cbxEm = new javax.swing.JComboBox<>();
        toolBar = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnEditar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnExcluir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnPesquisar = new javax.swing.JButton();
        spTableTarefa = new javax.swing.JScrollPane();
        tableTarefa = new br.com.tamarozzi.ui.table.TableTarefa();

        setName("Pessoas"); // NOI18N

        lblPeriodo.setText("Período:");

        lblDataDe.setText("Date de:");

        cbxDataDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadastro", "Vencimento", "Conclusão" }));

        lblTarefas.setText("Tarefas:");

        cbxTarefas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Minhas tarefas" }));
        cbxTarefas.setSelectedIndex(1);

        lblSituacao.setText("Situação:");

        cbxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Concluída", "Não concluída" }));
        cbxSituacao.setSelectedIndex(2);
        cbxSituacao.setMinimumSize(new java.awt.Dimension(70, 20));
        cbxSituacao.setPreferredSize(new java.awt.Dimension(70, 20));

        lblCategoria.setText("Categoria:");

        cbxCategoria.setMinimumSize(new java.awt.Dimension(125, 20));
        cbxCategoria.setPreferredSize(new java.awt.Dimension(125, 20));

        lblPesquisa.setText("Pesquisa:");

        lblEm.setText("Em:");

        cbxEm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Descrição", "Responsável" }));
        cbxEm.setMinimumSize(new java.awt.Dimension(125, 20));
        cbxEm.setPreferredSize(new java.awt.Dimension(125, 20));

        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-icon.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        toolBar.add(btnNovo);
        toolBar.add(jSeparator1);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar-icon.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        toolBar.add(btnEditar);
        toolBar.add(jSeparator2);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir-icon.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        toolBar.add(btnExcluir);
        toolBar.add(jSeparator3);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar-icon.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setFocusable(false);
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        toolBar.add(btnPesquisar);

        tableTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTarefaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableTarefaMousePressed(evt);
            }
        });
        spTableTarefa.setViewportView(tableTarefa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spTableTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategoria)
                    .addComponent(lblPeriodo)
                    .addComponent(lblTarefas)
                    .addComponent(lblPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxTarefas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxCategoria, 0, 180, Short.MAX_VALUE)
                        .addComponent(txtPesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtcDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataDe)
                    .addComponent(lblSituacao)
                    .addComponent(lblEm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxEm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxDataDe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPeriodo)
                    .addComponent(dtcDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtcDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataDe)
                    .addComponent(cbxDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTarefas)
                    .addComponent(cbxTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSituacao)
                    .addComponent(cbxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEm)
                    .addComponent(cbxEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTableTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
        );

        lblCategoria.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.editItem();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.deleteItem();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        this.tableTarefa.reload(
            this.tarefaController.getAllTarefa(
                this.listCampoFiltro.get(this.cbxEm.getSelectedIndex()),
                this.txtPesquisa.getText(),
                this.listSituacaoFiltro.get(this.cbxSituacao.getSelectedIndex()),
                this.listResponsaveisFiltro.get(this.cbxTarefas.getSelectedIndex()),
                this.listCategoriasFiltro.get(this.cbxCategoria.getSelectedIndex()).getUUID(),
                this.listTipoDataFiltro.get(this.cbxDataDe.getSelectedIndex()),
                this.dtcDataInicio.getDate(),
                this.dtcDataFim.getDate()
            )
        );
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.addItem(null);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void tableTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTarefaMouseClicked
        if(evt.getClickCount() == 2) {
            notifyObservers();
        }
    }//GEN-LAST:event_tableTarefaMouseClicked

    private void tableTarefaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTarefaMousePressed
        if(!this.btnEditar.isEnabled()) {
            this.btnEditar.setEnabled(true);
            this.btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_tableTarefaMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxDataDe;
    private javax.swing.JComboBox<String> cbxEm;
    private javax.swing.JComboBox<String> cbxSituacao;
    private javax.swing.JComboBox<String> cbxTarefas;
    private com.toedter.calendar.JDateChooser dtcDataFim;
    private com.toedter.calendar.JDateChooser dtcDataInicio;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDataDe;
    private javax.swing.JLabel lblEm;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTarefas;
    private javax.swing.JScrollPane spTableTarefa;
    private br.com.tamarozzi.ui.table.TableTarefa tableTarefa;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void registerObserver(Observer ob) {
        this.observers.add(ob);
        System.out.println("** Sistema: Observado " + this.getClass().getName() + " - Observador " + ob.getClass().getName() + " está registrado.");
    }

    @Override
    public void removeObserver(Observer ob) {
        this.observers.remove(ob);
        System.out.println("** Sistema: Observado " + this.getClass().getName() + " - Observador " + ob.getClass().getName() + " foi removido.");
    }

    @Override
    public void notifyObservers() {
        for(Observer ob : this.observers) {
            ob.update(this.tableTarefa.getTarefaSelected());
        }
    }

    @Override
    public void update(Object obj) {
        this.tableTarefa.addItem(obj);
    }

    @Override
    public void addItem(String tipoTarefa) {
        this.frmCadastroTarefa = new FrmCadastroTarefa();
        this.frmCadastroTarefa.registerObserver(this);
        this.frmCadastroTarefa.setVisible(true);
    }

    @Override
    public void editItem() {
        Tarefa tarefaSelected = this.tableTarefa.getTarefaSelected();
        
        if(tarefaSelected != null) {
            Tarefa t = this.tarefaController.getTarefa(tarefaSelected);
            new FrmCadastroTarefa(t).setVisible(true);
        }
    }

    @Override
    public void deleteItem() {
        List<Tarefa> tarefas = this.tableTarefa.getTarefasSelected();
        
        if(tarefas != null) {
            if(this.tarefaController.deleteTarefa(tarefas)) {
                this.tableTarefa.removeItens((List<Object>) (Object) tarefas);
            }
        }
    }
}
