/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tamarozzi.ui.panel;

import br.com.tamarozzi.controller.PessoaController;
import br.com.tamarozzi.model.Pessoa;
import br.com.tamarozzi.ui.FrmCadastroPessoa;
import br.com.tamarozzi.ui.table.model.PessoaTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Panda
 */
public class PanelPessoa extends javax.swing.JPanel {

    private final PessoaController pessoaController;
    private final PessoaTableModel pessoaTableModel;
    
    private final List<String> listCampoFiltro;
    private final List<String> listTipoPessoaFiltro;
    private final List<String> listSituacaoFiltro;
    
    /**
     * Creates new form PanelPessoa
     */
    public PanelPessoa() {
        this.listCampoFiltro = Arrays.asList("todos", "nome", "email");
        this.listTipoPessoaFiltro = Arrays.asList("todos", "F", "J");
        this.listSituacaoFiltro = Arrays.asList("todos", "1", "0");
        
        this.pessoaController = new PessoaController();
        this.pessoaTableModel = new PessoaTableModel();
                
        initComponents();
        setComponents();
    }
    
    private void setComponents() {
        this.tablePessoa.getColumnModel().getColumn(0).setMaxWidth(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenuPessoa = new javax.swing.JPopupMenu();
        mnuItemPessoaFisica = new javax.swing.JMenuItem();
        mnuItemPessoaJuridica = new javax.swing.JMenuItem();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        toolBarPessoa = new javax.swing.JToolBar();
        btnPessoaNovo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPessoaEditar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnPessoaExcluir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnPessoaPesquisar = new javax.swing.JButton();
        lblEm = new javax.swing.JLabel();
        cbxEm = new javax.swing.JComboBox<>();
        lblTipoPessoa = new javax.swing.JLabel();
        cbxTipoPessoa = new javax.swing.JComboBox<>();
        lblSituacao = new javax.swing.JLabel();
        cbxSituacao = new javax.swing.JComboBox<>();
        spTablePessoa = new javax.swing.JScrollPane();
        tablePessoa = new javax.swing.JTable();

        mnuItemPessoaFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-icon.png"))); // NOI18N
        mnuItemPessoaFisica.setText("Pessoa Física");
        mnuItemPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPessoaFisicaActionPerformed(evt);
            }
        });
        popMenuPessoa.add(mnuItemPessoaFisica);

        mnuItemPessoaJuridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-icon.png"))); // NOI18N
        mnuItemPessoaJuridica.setText("Pessoa Jurídica");
        popMenuPessoa.add(mnuItemPessoaJuridica);

        setName("Pessoas"); // NOI18N

        lblPesquisa.setText("Pesquisa:");

        toolBarPessoa.setFloatable(false);
        toolBarPessoa.setRollover(true);

        btnPessoaNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-icon.png"))); // NOI18N
        btnPessoaNovo.setText("Novo");
        btnPessoaNovo.setFocusable(false);
        btnPessoaNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPessoaNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPessoaNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPessoaNovoMousePressed(evt);
            }
        });
        toolBarPessoa.add(btnPessoaNovo);
        toolBarPessoa.add(jSeparator1);

        btnPessoaEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar-icon.png"))); // NOI18N
        btnPessoaEditar.setText("Editar");
        btnPessoaEditar.setEnabled(false);
        btnPessoaEditar.setFocusable(false);
        btnPessoaEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPessoaEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPessoaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoaEditarActionPerformed(evt);
            }
        });
        toolBarPessoa.add(btnPessoaEditar);
        toolBarPessoa.add(jSeparator2);

        btnPessoaExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir-icon.png"))); // NOI18N
        btnPessoaExcluir.setText("Excluir");
        btnPessoaExcluir.setEnabled(false);
        btnPessoaExcluir.setFocusable(false);
        btnPessoaExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPessoaExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPessoaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoaExcluirActionPerformed(evt);
            }
        });
        toolBarPessoa.add(btnPessoaExcluir);
        toolBarPessoa.add(jSeparator3);

        btnPessoaPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar-icon.png"))); // NOI18N
        btnPessoaPesquisar.setText("Pesquisar");
        btnPessoaPesquisar.setFocusable(false);
        btnPessoaPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPessoaPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPessoaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoaPesquisarActionPerformed(evt);
            }
        });
        toolBarPessoa.add(btnPessoaPesquisar);

        lblEm.setText("Em:");

        cbxEm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nome", "E-mail" }));
        cbxEm.setMinimumSize(new java.awt.Dimension(125, 20));
        cbxEm.setPreferredSize(new java.awt.Dimension(125, 20));

        lblTipoPessoa.setText("Tipo:");

        cbxTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pessoa Física", "Pessoa Juridica", "Empresa do Sistema", "Usuario do Sistema" }));
        cbxTipoPessoa.setMinimumSize(new java.awt.Dimension(125, 20));
        cbxTipoPessoa.setPreferredSize(new java.awt.Dimension(125, 20));

        lblSituacao.setText("Situação:");

        cbxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Ativo", "Inativo" }));
        cbxSituacao.setMinimumSize(new java.awt.Dimension(70, 20));
        cbxSituacao.setPreferredSize(new java.awt.Dimension(70, 20));

        tablePessoa.setModel(pessoaTableModel);
        tablePessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePessoaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablePessoaMousePressed(evt);
            }
        });
        spTablePessoa.setViewportView(tablePessoa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spTablePessoa, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolBarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipoPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSituacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoPessoa)
                    .addComponent(cbxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEm)
                    .addComponent(cbxEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSituacao)
                    .addComponent(cbxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolBarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(spTablePessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPessoaNovoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPessoaNovoMousePressed
        this.popMenuPessoa.show(this.btnPessoaNovo, evt.getX(), evt.getY());
    }//GEN-LAST:event_btnPessoaNovoMousePressed

    private void btnPessoaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoaEditarActionPerformed
        this.editPessoa();
    }//GEN-LAST:event_btnPessoaEditarActionPerformed

    private void btnPessoaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoaExcluirActionPerformed
        this.deletePessoa();
    }//GEN-LAST:event_btnPessoaExcluirActionPerformed

    private void btnPessoaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoaPesquisarActionPerformed
        this.pessoaTableModel.reload(
            this.pessoaController.getAllPessoa(
                this.listCampoFiltro.get(this.cbxEm.getSelectedIndex()),
                this.txtPesquisa.getText(),
                this.listTipoPessoaFiltro.get(this.cbxTipoPessoa.getSelectedIndex()),
                this.listSituacaoFiltro.get(this.cbxSituacao.getSelectedIndex())
            )
        );
    }//GEN-LAST:event_btnPessoaPesquisarActionPerformed

    private void tablePessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePessoaMouseClicked
        if(evt.getClickCount() == 2) {
            this.editPessoa();
        }
    }//GEN-LAST:event_tablePessoaMouseClicked

    private void tablePessoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePessoaMousePressed
        if(!this.btnPessoaEditar.isEnabled()) {
            this.btnPessoaEditar.setEnabled(true);
            this.btnPessoaExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_tablePessoaMousePressed

    private void mnuItemPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPessoaFisicaActionPerformed
        Pessoa p = new Pessoa();

        FrmCadastroPessoa form = new FrmCadastroPessoa(p);
        form.setVisible(true);
        form.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent evt) {
                if(p.getId() > 0)
                pessoaTableModel.addPessoa(p);
            }
        });
    }//GEN-LAST:event_mnuItemPessoaFisicaActionPerformed

    private void deletePessoa() {
        List<Pessoa> pessoas = this.pessoaTableModel.getPessoasSelected(this.tablePessoa.getSelectedRows());
        
        if(pessoas != null) {
            if(this.pessoaController.deletePessoa(pessoas)) {
                this.pessoaTableModel.removePessoa(pessoas);
            }
        }
    }
    
    private void editPessoa() {
        Pessoa pessoaSelected = this.getPessoaSelected();
        
        if(pessoaSelected != null) {
            Pessoa p = this.pessoaController.getPessoa(pessoaSelected);
            new FrmCadastroPessoa(p).setVisible(true);
        }
    }
    
    public Pessoa getPessoaSelected() {
        int index = this.tablePessoa.getSelectedRow();
        
        if(index >= 0) {
            return this.pessoaTableModel.getPessoaSelected(index);
        }
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPessoaEditar;
    private javax.swing.JButton btnPessoaExcluir;
    private javax.swing.JButton btnPessoaNovo;
    private javax.swing.JButton btnPessoaPesquisar;
    private javax.swing.JComboBox<String> cbxEm;
    private javax.swing.JComboBox<String> cbxSituacao;
    private javax.swing.JComboBox<String> cbxTipoPessoa;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel lblEm;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTipoPessoa;
    private javax.swing.JMenuItem mnuItemPessoaFisica;
    private javax.swing.JMenuItem mnuItemPessoaJuridica;
    private javax.swing.JPopupMenu popMenuPessoa;
    private javax.swing.JScrollPane spTablePessoa;
    public javax.swing.JTable tablePessoa;
    private javax.swing.JToolBar toolBarPessoa;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
